  
name: "{{ROUTE}}"

on:
  pull_request:
    types: [opened,synchronize,closed]
    branches: [master]
    paths:
      - "{{ROUTE}}/**"
      - ".github/workflows/{{ROUTE}}.yml"

# jobs:
#   run-build-test-lint-publish-package:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         node-version: [14.x]
#     steps:
#       - uses: actions/checkout@v2

#       - name: Install Dependencies
#         run: |
#           npm install