name: Changelog Generator
on:
  push:
  pull_request:
    types: [opened,synchronize,closed]
jobs:
  un-build-test-lint-publish-package:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Publish package
        run: |
          npm publish
        env:
          NODE_AUTH_TOKEN: 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

