name: Changelog Generator
on:
  push:
  # Trigger workflow when a pull request is created/updated/merged
  pull_request:
    types: [opened,synchronize,closed]
jobs:
  un-build-test-lint-publish-package:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Extract version
        id: extract_version
        uses: Saionaro/extract-package-version@v1.0.6
        
      # From now you can access the version
      - name: Print version
        run: echo ${{ steps.extract_version.outputs.version }}
