name: Changelog Generator
on:
  # Trigger workflow when a pull request is created/updated/merged
  pull_request:
    types: [opened,synchronize,closed]
jobs:
  changelog:
    name: Chanegelog Generator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Env Variable
        run: printenv
        env:
          isPublished : true
          merged : true
          event: 'pull_request'
          
      - run: printenv
      - if: ${isPublished} == false && ${merged} == true && ${event} == 'pull_request'
        run: echo hi...
