name: Changelog Generator
on:
  push:
  # Trigger workflow when a pull request is created/updated/merged
  pull_request:
    types: [opened,synchronize,closed]
jobs:
  un-build-test-lint-publish-package:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - uses: nyaa8/package-version@v1
        with:
          path: 'uwu/package.json' # Optional
          follow-symlinks: 'false' # Optional
      - run: echo ${{ env.PACKAGE_VERSION }}
