name: Changelog Generator
on:
  pull_request:
jobs:
  changelog:
    name: Chanegelog Generator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bala-raj/pull-request-changelog@mbranch
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'dev'
      - name: Find Comment
        uses: peter-evans/find-comment@v1
        id: fc
        with:
          issue-number: ${{ github.event.number }}
          comment-author: github-actions[bot]
          direction: last

#       - run: |
#           echo ${{ steps.fc.outputs.comment-id }}
#           echo ${{ steps.fc.outputs.comment-body }}
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.fc.outputs.comment-id }} # Get version from package.json
          release_name: ${{ steps.fc.outputs.comment-id }}
          body: | # Changes or features in the corresponding release
            ${{ steps.fc.outputs.comment-body }}
          draft: false
          prerelease: false # This is not a prerelease so set false
