name: Publish a package
on:
  push:
jobs:
  run-build-test-lint-publish-package:
#     if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Test
        run: |
          printenv
          
      - name: Get package published or not
        uses: flood-io/is-published-on-npm@v1
        id: is-published
        
      - name: Check version
        run: |
          echo steps.is-published.outputs.published
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
