name: Changelog Generator
on:
  push:
  pull_request:
    types: [opened,synchronize,closed]
permissions:
  contents: read
  packages: write
  pull-requests: write
jobs:
  un-build-test-lint-publish-package:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Publish package
        run: |
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

