name: Publish a package
on:
  pull_request:
    types: [closed]
    branches: [master]
jobs:
  run-build-test-lint-publish-package:
    if: github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'master'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Test
        run: |
          printenv