name: Publish a package
on:
  push:
jobs:
  run-build-test-lint-publish-package:
#     if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Test
        run: |
          printenv
          
      - name: Check package version
        uses: PostHog/check-package-version@v2
        with:
          path: .
        id: CheckVersion
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        
      - name: Echo output
        run: |
            echo "Committed version: ${{ steps.CheckVersion.outputs.committed-version }}"
            echo "Published version: ${{ steps.CheckVersion.outputs.published-version }}"
            echo "Is new version: ${{ steps.CheckVersion.outputs.is-new-version }}"
      
      
