name: Changelog Generator
on:
  push:
  # Trigger workflow when a pull request is created/updated/merged
  pull_request:
    types: [opened,synchronize,closed]
jobs:
  changelog:
    name: Chanegelog Generator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate Change logs
        uses: bala-raj/pull-request-changelog@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch:  ${{ github.event.pull_request.base.ref }}
          
      - if: ${{ steps.isPublished.outputs.published }} == false 
        name: Get Change logs from Comment
        uses: peter-evans/find-comment@v1
        id: fetchComment
        with:
          issue-number: ${{ github.event.number }}
          comment-author: github-actions[bot]
          direction: last
          
      - if: ${{ steps.fetchComment.outputs.comment-id }} && github.event_name == 'pull_request' && github.event.pull_request.merged == 'true'
        run: echo ${{ github.event.pull_request.base.ref }}
