name: Changelog Generator
on:
  push:
  # Trigger workflow when a pull request is created/updated/merged
  pull_request:
    types: [opened,synchronize,closed]
jobs:
  un-build-test-lint-publish-package:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Get package History
        uses: flood-io/is-published-on-npm@v1
        id: isPublished
