name: Changelog Generator
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  changelog:
    name: Chanegelog Generator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Change log
        uses: bala-raj/pull-request-changelog@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch:  ${{ github.event.pull_request.base.ref }}
