name: Changelog Generator
on:
  # Trigger workflow when a pull request is created/updated/merged
  pull_request:
    types: [opened,synchronize,closed]
jobs:
  un-build-test-lint-publish-package:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - run: echo ${{ github.event.pull_request.base.ref }}
      - name: Change log
        uses: bala-raj/pull-request-changelog@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch:  ${{ github.event.pull_request.base.ref }}
