  
name: repo-1

on:
  pull_request:
    types: [opened,synchronize,closed]
jobs:
  run-build-test-lint-publish-package:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2

      - name: Inside repo-1
        run: echo inside repo-1

      - name: Install Dependencies
        run: |
          cd repo-1
          npm install
          ls -a
          cd node_modules
          ls -a
          
      - name: Delete merged branch
        uses: koj-co/delete-merged-action@master
        with:
          branches: "!mono-repo"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Get package History
        uses: cd repo-1 && flood-io/is-published-on-npm@v1
        id: isPublished

