  
name: repo-1

on:
  pull_request:
    types: [opened,synchronize,closed]
jobs:
  run-build-test-lint-publish-package:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2

      - name: Inside repo-1
        run: echo inside repo-1

      - name: Install Dependencies
        run: |
          cd repo-1
          npm install
          ls -a
          cd node_modules
          ls -a
          
      - run: curl --silent "https://api.github.com/repos/$1/releases/latest"
      
#       - name: CWD
#         run: ls -a
        
#       - name: CWD
#         run: pwd
          
#       - name: Check
#         id: check
#         uses: rzane/is-unpublished@v0.3.3
#         with:
#           cwd: ./repo-1/package.json
          
#       - run: echo ${{ steps.check.outputs.is-unpublished == 'true' }}
#       - run: echo ${{ steps.check.outputs.version}}      
