  
name: "repo-2"

on:
  pull_request:
    types: [opened,synchronize,closed]
    paths:
      - "repo-2/**"
      - ".github/workflows/repo-2.yml"

jobs:
  run-build-test-lint-publish-package:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2

      - name: Inside repo-2
        run: echo inside repo-2

      - name: Install Dependencies
        run: |
          cd repo-2
          npm install
